cart/urls.py
from django.urls import path
from cart.views import CartSummaryView, CartAddView, CartDeleteView, RentAllBooksView, RentBookView
app_name = "cart"
urlpatterns = [
    path('', CartSummaryView.as_view(), name='cart_summary'),
    path('add/', CartAddView.as_view(), name='cart_add'),
    path('delete/', CartDeleteView.as_view(), name='cart_delete'),
    path('rent-book/', RentBookView.as_view(), name='rent_book'),
    path('rent-all-books/', RentAllBooksView.as_view(), name='rent_all_books'),
]

django_library/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    path('cart/', include('cart.urls')),
    path('reviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/urls.py
from django.urls import path

from library.views import AboutView, BookView, CategoryView, HomeView, LoginUserView, LogoutUserView, MyBooksView, RegisterUserView, ReportView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('book/<int:pk>', BookView.as_view(), name='book'),
    path('category/<str:foo>', CategoryView.as_view(), name='category'),
    path('my-books/', MyBooksView.as_view(), name='my_books'),
    path('report/', ReportView.as_view(), name='report'),
]

reviews/urls.py
from django.urls import path
from reviews.views import ReviewListView, AddReviewView, EditReviewView, DeleteReviewView

app_name = 'reviews'
urlpatterns = [
    path('list/', ReviewListView.as_view(), name='review_list'),
    path('<int:book_id>/add/', AddReviewView.as_view(), name='add_review'),
    path('edit/<int:review_id>/', EditReviewView.as_view(), name='edit_review'),
    path('delete/<int:review_id>/', DeleteReviewView.as_view(), name='delete_review'),
]

library/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    is_approved = models.BooleanField(default=False)


class Category(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
    
    class Meta:
        verbose_name_plural = 'categories'
    
    
class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    image = models.ImageField(upload_to='uploads/book/')
    quantity = models.PositiveIntegerField(default=1)
    
    def __str__(self):
        return self.title
    
    def average_stars(self):
        reviews = self.review_set.all()
        if reviews:
            return sum(review.stars for review in reviews) / len(reviews)
        return 0
    

class BookInstance(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    is_returned = models.BooleanField(default=False)
    start_date = models.DateField()
    end_date = models.DateField()
    borrower = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    
    def save(self, *args, **kwargs):
        if not self.pk:
            self.book.quantity -= 1
            self.book.save()
        elif self.is_returned:
            self.book.quantity += 1
            self.book.save()

        super().save(*args, **kwargs)
    
    def delete(self, *args, **kwargs):
        if not self.is_returned:
            self.book.quantity += 1
            self.book.save()

        super().delete(*args, **kwargs)
    
    def __str__(self):
        return f"{self.book.title}"

library/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from library.models import CustomUser

class SignUpForm(UserCreationForm):
	email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email Address'}))
	first_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}))
	last_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}))

	class Meta:
		model = CustomUser
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

	def __init__(self, *args, **kwargs):
		super(SignUpForm, self).__init__(*args, **kwargs)

		self.fields['username'].widget.attrs['class'] = 'form-control'
		self.fields['username'].widget.attrs['placeholder'] = 'User Name'
		self.fields['username'].label = ''
		self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

		self.fields['password1'].widget.attrs['class'] = 'form-control'
		self.fields['password1'].widget.attrs['placeholder'] = 'Password'
		self.fields['password1'].label = ''
		self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

		self.fields['password2'].widget.attrs['class'] = 'form-control'
		self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
		self.fields['password2'].label = ''
		self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'

library/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import DetailView, TemplateView
from library.decorators import staff_required
from library.models import Book, BookInstance, Category
from reviews.models import Review
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from library.forms import SignUpForm


class HomeView(TemplateView):
    template_name = 'home.html'
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['books'] = Book.objects.all().order_by('-id')
        return context


class AboutView(TemplateView):
    template_name = 'about.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    
    
class CategoryView(TemplateView):
    template_name = 'category.html'
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        category_name = kwargs.get('foo').replace('-', ' ')
        try:
            category = Category.objects.get(name=category_name)
            books = Book.objects.filter(category=category)
            return render(request, self.template_name, {'books': books})
        except Category.DoesNotExist:
            messages.error(request, 'That category does not exist')
            return redirect('home')


        
class BookView(DetailView):
    model = Book
    template_name = 'book.html'
    context_object_name = 'book'
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        reviews = Review.objects.filter(book=self.object)
        
        context['reviews'] = reviews
        return context
    

class LoginUserView(View):
    template_name = 'login.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            if user.is_approved:
                login(request, user)
                messages.success(request, ("You have been logged in"))
                return redirect('home')
            else:
                messages.error(request, "Your account is not approved. Please wait for approval.")
                return redirect('login')
        else:
            messages.error(request, ("Invalid username or password"))
            return redirect('login')


class LogoutUserView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('login')
    
class RegisterUserView(View):
    template_name = 'register.html'

    def get(self, request, *args, **kwargs):
        form = SignUpForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            messages.success(request, ("You have registered successfully! You have to wait for an admin to approve the sign up process!"))
            return redirect('home')
        else:
            error_messages = form.errors.as_text()
            messages.error(request, f"There was an error signing up: {error_messages}")
            return render(request, self.template_name, {'form': form})



class MyBooksView(TemplateView):
    template_name = 'my_books.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        rented_books = BookInstance.objects.filter(borrower=self.request.user)
        
        for book_instance in rented_books:
            review = book_instance.book.review_set.filter(user=self.request.user).first()
            book_instance.has_reviewed = review.id if review else None


        context['rented_books'] = rented_books
        
        return context



class ReportView(TemplateView):
    template_name = 'report.html'
    
    @method_decorator(staff_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        rented_books = BookInstance.objects.filter(is_returned=False)
        available_books = Book.objects.filter(quantity__gt=0)
        all_books = Book.objects.all()
        context['rented_books'] = rented_books
        context['available_books'] = available_books
        context['all_books'] = all_books
        return context

library/templates/about.html
{% extends 'base.html' %}
{% block content %}
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">About Us...</h1>
                <p class="lead fw-normal text-white-50 mb-0">Welcome to Palalele Library</p>
            </div>
        </div>
    </header>

    <div class="container">
        <div class="row">
            <center>
                <div class="col-8">
                    <br /><br />
                    <p align="justify">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin quam aliquet suscipit pulvinar. Etiam purus nisl, accumsan vel sodales sit amet, pellentesque vitae dui. Duis posuere cursus mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam malesuada ligula ex, sed condimentum mi venenatis non. Ut nisi purus, pellentesque molestie commodo ut, pulvinar eget dolor. Nunc condimentum nisi mi, nec placerat enim condimentum convallis. Vivamus non sem felis. Suspendisse semper dignissim justo non suscipit. Duis tempus lacus neque, at volutpat mi scelerisque sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget blandit nibh, eu sodales turpis. Phasellus condimentum euismod nisi, sit amet tincidunt erat posuere ut. Sed vitae accumsan velit. Quisque placerat, neque iaculis laoreet aliquet, est magna sollicitudin arcu, at congue dui justo eu libero.
                        <br /> <br />
                        Integer at arcu a felis dignissim lobortis. Nam luctus fringilla est aliquam pretium. Vestibulum non finibus felis, ac sagittis nibh. Morbi lacinia augue ac ante ultrices, at tempus quam auctor. Suspendisse in neque dolor. Ut id sagittis justo. Integer nec purus odio. Etiam vestibulum dapibus erat, vitae luctus lacus efficitur tempor. Pellentesque lacinia at diam vitae consectetur. Curabitur suscipit tempus ante nec volutpat.
                        <br /> <br />
                        Aliquam sit amet mauris felis. Ut ac libero odio. Sed pharetra in eros sit amet convallis. Duis quam nulla, cursus sed lorem ut, semper iaculis neque. Duis ultrices porttitor leo, eu mollis purus accumsan sit amet. Nulla finibus semper luctus. Nunc sit amet leo vel tortor sagittis scelerisque a id leo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed velit diam, condimentum ac magna eu, viverra pellentesque ante. Ut imperdiet massa eget ornare tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nunc et nulla sodales, pharetra felis nec, pretium nulla. Fusce mattis tempor lorem at finibus. Aenean fermentum massa in diam posuere ultrices.
                    </p>
                    <br /><br />
                </div>
            </center>
        </div>
    </div>


{% endblock %}

library/templates/base.html
{% load static %}
{% load fontawesome_5 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% fontawesome_5_static %} 
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Palalele Library</title>
    <link
      rel="icon"
      type="image/x-icon"
      href="{% static 'assets/favicon.ico' %}"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
      rel="stylesheet"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <script
      src="https://code.jquery.com/jquery-3.7.1.min.js"
      integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css"
    />
    <script
      type="text/javascript"
      charset="utf8"
      src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"
    ></script>
  </head>
  <body>
    {% include 'navbar.html' %}
    <main>
      {% if messages %} {% for message in messages %}
      <div class="position-fixed top-0 end-0 p-2" style="max-width: 300px">
        {% if message.tags == 'success' %}
        <div
          class="alert alert-success alert-dismissible fade show"
          role="alert"
        >
          {{ message }}
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="alert"
            aria-label="Close"
          ></button>
        </div>
        {% elif message.tags == 'error' %}
        <div
          class="alert alert-danger alert-dismissible fade show"
          role="alert"
        >
          {{ message }}
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="alert"
            aria-label="Close"
          ></button>
        </div>
        {% elif message.tags == 'warning' %}
        <div
          class="alert alert-warning alert-dismissible fade show"
          role="alert"
        >
          {{ message }}
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="alert"
            aria-label="Close"
          ></button>
        </div>
        {% else %}
        <!-- Default style for other message types -->
        <div class="alert alert-info alert-dismissible fade show" role="alert">
          {{ message }}
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="alert"
            aria-label="Close"
          ></button>
        </div>
        {% endif %}
      </div>
      {% endfor %} {% endif %} {% block content %} {% endblock %}
    </main>
    <footer class="py-5 bg-dark footer-base">
      <div class="container">
        <p class="m-0 text-center text-white">
          Copyright &copy; Palalele Library 2023
        </p>
      </div>
    </footer>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js/scripts.js' %}"></script>
  </body>
</html>

library/templates/book.html
{% extends 'base.html' %}
{% block content %}

    <div class="">
        <br/><br/>
        <div class="container">
            <div class="card mb-3" >
                <div class="row g-0">
                  <div class="col-md-4">
                    <div class="image-container">
                      <img src="{{ book.image.url }}" class="img-fluid rounded-start custom-image" alt="...">
                    </div>
                  </div>
                  <div class="col-md-8 d-flex align-items-center">
                    <div class="card-body">
                        <center>
                            <br/>
                            <h2 class="card-title">{{ book.title }}</h2>
                            <br/>
                            <p class="card-text" >{{ book.description }}</p>
                            <br/>
                            Author: {{ book.author }}
                            <br/>
                            <div class="row justify-content-center">
                            </div>
                                
                            <br/> <br/>
                            <a href="{% url 'home' %}" class="btn btn-dark">Home</a>
                            <button type="button" value="{{ book.id }}" id="add-cart" class="btn btn-dark">Add to Cart</button>
                            <br/><br/>
                        </center>
                    </div>
                  </div>
                </div>
              </div>
              <div class="my-4">
                <h3 class="mb-3">Reviews:</h3>
                {% if reviews %}
                    <ul class="list-group">
                        {% for review in reviews %}
                            <li class="list-group-item">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                        <h6 class="mb-0">{{ review.title }}</h6>
                                        <p class="mb-1 text-muted">{{ review.user.username }} - {{ review.stars }} stars</p>
                                        <p class="mb-0">{{ review.description }}</p>
                                    </div>
                                    <!-- Add any additional information or styling here -->
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p class="text-muted">No reviews yet.</p>
                {% endif %}
            </div>
        </div>
    </div>

<script>
  $(document).ready(function(){
    $(document).on('click', '#add-cart', function(e){
      e.preventDefault();
      $.ajax({
        type: 'POST',
        url: "{% url 'cart:cart_add' %}",
        data: {
          book_id: $('#add-cart').val(),
          csrfmiddlewaretoken: '{{ csrf_token }}',
          action: 'post',
        },
  
        success: function(json) {
          document.getElementById('cart_quantity').textContent = json.qty
        },
  
        error: function(xhr, errmsg, err){
  
        },
  
      });
    })
  });

</script>

{% endblock %}

library/templates/category.html
{% extends 'base.html' %}
{% block content %}
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">{{ category }}</h1>
                <p class="lead fw-normal text-white-50 mb-0">Category Page</p>
            </div>
        </div>
    </header>
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">

            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for book in books %}
                <div class="col mb-5">
                    <div class="card h-100">
                        <div class="image-container-card">
                            <img class="card-img-top custom-image-card" src="{{ book.image.url }}" alt="..." />
                        </div>
                        <div class="card-body p-4">
                            <div class="text-center">
                                <h5 class="fw-bolder">{{ book.title }}</h5>
                                by {{ book.author }}
                                <div>Quantity: {{ book.quantity }}</div>
                            </div>
                        </div>
                        {% if book.quantity > 0 %}
                            <div class="badge bg-success text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Book available</div>
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center">
                                    <a class="btn btn-outline-dark mt-auto" href="{% url 'book' book.id %}">View Book</a>
                                </div>
                            </div>
                        {% else %}
                            <div class="badge bg-danger text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Book not available</div>
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center">
                                    <p class="text-danger">Not Available</p>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

library/templates/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="bg-dark min-vh-100">
    <header class="py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Log In</h1>
                <p class="lead fw-normal text-white-50 mb-0">Log In into your account</p>
            </div>
        </div>
    </header>

        <div class="container">
            <div class="row">
                <div class="col-6 mx-auto">
                    <br />
                    <form method="POST" action="{% url 'login' %}" class="border p-4 rounded bg-white">
                        {% csrf_token %}
                        <div class="form-group mb-3">
                            <label for="username" class="form-label text-start">Username</label>
                            <input type="text" class="form-control" name="username" placeholder="Enter your username">
                        </div>
                        <div class="form-group mb-3">
                            <label for="password" class="form-label text-start">Password</label>
                            <input type="password" class="form-control" name="password" placeholder="Enter your password">
                        </div>
                        <br />
                        <div class="text-center">
                            <button type="submit" class="btn btn-secondary">Login</button>
                        </div>
                    </form>
                </div>
                
            </div>
        </div>
    </div>


{% endblock %}

library/templates/my_books.html
{% extends 'base.html' %} {% block content %}
<header class="bg-dark py-5">
  <div class="container px-4 px-lg-5 my-5">
    <div class="text-center text-white">
      <h1 class="display-4 fw-bolder">My Books</h1>
      <p class="lead fw-normal text-white-50 mb-0">View your rented books...</p>
    </div>
  </div>
</header>
<br />
<div class="container">
  {% if rented_books %}
  <div
    class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-3 justify-content-center"
  >
    {% for book_instance in rented_books %}
    <div class="col mb-5">
      <div class="card h-100">
        <img
          src="{{ book_instance.book.image.url }}"
          class="card-img-top img-fluid rounded-top custom-image"
          alt="..."
        />
        <div class="card-body">
          <h3 class="card-title">{{ book_instance.book.title }}</h3>
          <p class="card-text">Author: {{ book_instance.book.author }}</p>
          <strong>Rent period</strong>
          <p class="card-text">
            {{ book_instance.start_date }} -> {{ book_instance.end_date }}
          </p>
          <strong>Is returned:</strong>
          {% if book_instance.is_returned %}
          <div class="icon-cell green-bg d-inline-block mb-2">
            <span class="icon">&#10004;</span>
          </div>
          {% else %}
          <div class="icon-cell red-bg d-inline-block mb-2">
            <span class="icon">&#10006;</span>
          </div>

          {% endif %}
          <a
            href="{% url 'book' book_instance.book.id %}"
            class="btn btn-dark d-block"
            >Book details</a
          >

          {% if book_instance.has_reviewed %}
            <a href="{% url 'reviews:edit_review' book_instance.has_reviewed %}" class="btn btn-warning d-block my-2">Edit Review</a>
          {% else %}
            <a href="{% url 'reviews:add_review' book_instance.book.id %}" class="btn btn-primary d-block my-2">Add Review</a>
          {% endif %}


          <!-- <a href="{% if book_instance.has_reviewed %}{% url 'reviews:edit_review' book_instance.has_reviewed %}{% else %}{% url 'reviews:add_review' book_instance.book.id %}{% endif %}"
          class="btn btn-primary d-block my-2">
          {% if book_instance.has_reviewed %}Edit Review{% else %}Add Review{% endif %} -->
        </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <p>You haven't rented any books yet.</p>
  {% endif %}
</div>

<script></script>

{% endblock %}

library/templates/navbar.html
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'home' %}">Palalele Library</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">About</a></li>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Categories</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'home' %}">All Books</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                
                                {% for category in categories %}
                                    <li><a class="dropdown-item" href="{% url 'category' category.name %}">{{ category.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'my_books' %}">My Books</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'reviews:review_list' %}">My Reviews</a></li>
                        
                        {% if user.is_staff %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'report' %}">Report</a></li>
                        {% endif %}

                    {% endif %}
                    {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Register</a></li>
                    {% endif %}
                    </ul>
                    {% if user.is_authenticated %}
                    <form class="d-flex">
                        <a href="{% url 'cart:cart_summary' %}" class="btn btn-outline-dark"><i class="bi-cart-fill me-1"></i>
                            Books to rent
                            <span class="badge bg-dark text-white ms-1 rounded-pill" id="cart_quantity">{{ cart|length }}</span>
                        </a>
                    </form>
                    {% endif %}
                </div>
            </div>
        </nav>