cart/urls.py
from django.urls import path
from cart.views import CartSummaryView, CartAddView, CartDeleteView, RentAllBooksView, RentBookView
app_name = "cart"
urlpatterns = [
    path('', CartSummaryView.as_view(), name='cart_summary'),
    path('add/', CartAddView.as_view(), name='cart_add'),
    path('delete/', CartDeleteView.as_view(), name='cart_delete'),
    path('rent-book/', RentBookView.as_view(), name='rent_book'),
    path('rent-all-books/', RentAllBooksView.as_view(), name='rent_all_books'),
]

django_library/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    path('cart/', include('cart.urls')),
    path('reviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.decorators import method_decorator
from django.views import View
from django.http import JsonResponse
from django.contrib import messages
from library.models import Book, BookInstance
from cart.cart import Cart
import datetime

class CartSummaryView(View):
    template_name = 'cart_summary.html'
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        cart = Cart(request)
        cart_books = cart.get_books
        return render(request, self.template_name, {'cart_books': cart_books})

class CartAddView(View):
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        cart = Cart(request)
        if request.POST.get('action') == 'post':
            book_id = int(request.POST.get('book_id'))
            book = get_object_or_404(Book, id=book_id)
            cart.add(book=book)
            cart_quantity = cart.__len__()
            response = JsonResponse({"qty": cart_quantity})
            return response

class CartDeleteView(View):
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        cart = Cart(request)
        if request.POST.get('action') == 'post':
            book_id = int(request.POST.get('book_id'))
            cart.delete(book_id)
            response = JsonResponse({'book': book_id})
            return response

class RentBookView(View):
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    
    def can_rent_book(self, user):
        return BookInstance.objects.filter(borrower=user, is_returned=False).count() < 5
    
    def post(self, request, *args, **kwargs):
        cart = Cart(request)
        if request.POST.get('action') == 'post':
            book_id = int(request.POST.get('book_id'))
            book = get_object_or_404(Book, id=book_id)
            
            if not self.can_rent_book(request.user):
                response = JsonResponse({'success': False, 'message': 'You have reached the maximum limit of rented books.'})
                messages.error(request, 'You have reached the maximum limit of rented books.')
                return response

            existing_instance = BookInstance.objects.filter(book=book, borrower=request.user, is_returned=False).first()
            if existing_instance:
                response = JsonResponse({'success': False, 'message': 'You have already rented this book and it is not returned.'})
                messages.error(request, ("You have already rented this book and it is not returned."))
                return response

            if book.quantity > 0:
                BookInstance.objects.create(
                    book=book,
                    start_date=datetime.date.today(),
                    end_date=datetime.date.today() + datetime.timedelta(days=14),
                    borrower=request.user
                )
                cart.delete(book_id)
                messages.success(request, f'You rented {book.title}')
                return redirect('cart:cart_summary')
            else:
                response = JsonResponse({'success': False, 'message': 'The book is not available for rent.'})
                messages.error(request, ('The book is not available for rent.'))
                return response

        return redirect('home')

class RentAllBooksView(View):
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    
    def can_rent_book(self, user):
        return BookInstance.objects.filter(borrower=user, is_returned=False).count() < 5

    def post(self, request, *args, **kwargs):
        cart = Cart(request)
        user = request.user
        books = cart.get_books()
        print(books)
        for book in books:
            existing_instance = BookInstance.objects.filter(book=book, borrower=user, is_returned=False).first()

            if not self.can_rent_book(request.user):
                response = JsonResponse({'success': False, 'message': 'You have reached the maximum limit of rented books.'})
                messages.error(request, ('You have reached the maximum limit of rented books.'))
                return response
            
            if not existing_instance:
                if book.quantity > 0:
                    BookInstance.objects.create(
                        book=book,
                        start_date=datetime.date.today(),
                        end_date=datetime.date.today() + datetime.timedelta(days=14),
                        borrower=user
                    )
                    cart.delete(book.id)

        response = JsonResponse({'success': True, 'message': 'All books rented successfully.'})
        messages.success(request, ('All books rented successfully.'))
        return response

cart/templates/cart_summary.html
{% extends 'base.html' %} {% block content %}
<header class="bg-dark py-5">
  <div class="container px-4 px-lg-5 my-5">
    <div class="text-center text-white">
      <h1 class="display-4 fw-bolder">Books to rent</h1>
      <p class="lead fw-normal text-white-50 mb-0">View your cart...</p>
    </div>
  </div>
</header>
<br />
<div class="container">
  {% if cart_books %}
  <div class="row">
    {% for book in cart_books %}
    <div class="col-12 mb-4">
      <div class="card w-75 mx-auto">
        <div class="row g-0">
          <div class="col-md-4">
            <div class="image-container">
              <img
                src="{{ book.image.url }}"
                class="img-fluid rounded-start custom-image"
                alt="..."
              />
            </div>
          </div>
          <div class="col-md-8 d-flex align-items-center">
            <div class="card-body">
              <center>
                <br />
                <h5 class="card-title">{{ book.title }}</h5>
                <br />
                <p class="card-text">{{ book.description|truncatewords:30 }}</p>
                <br />
                Author: {{ book.author }}
                <br />
                <div class="row justify-content-center"></div>

                <br />
                <br />
                <a href="{% url 'book' book.id %}" class="btn btn-dark"
                  >Book details</a
                >
                <button
                  type="button"
                  data-index="{{ book.id }}"
                  class="btn btn-danger delete-book"
                >
                  Delete
                </button>
                <button
                  type="button"
                  data-index="{{ book.id }}"
                  class="btn btn-success rent-book"
                >
                  Rent Book
                </button>
                <br /><br />
              </center>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
    <center>
      <div class="col-md-8">
        <button
          type="button"
          id="rent-all-books"
          class="btn btn-success rent-all-books"
        >
          Rent All
        </button>
      </div>
    </center>
  </div>
  {% else %} There's Nothing In Your Cart... {% endif %}
</div>

<script>
  $(document).ready(function () {
    $(document).on("click", ".delete-book", function (e) {
      e.preventDefault();

      if (confirm("Are you sure you want to delete this book from the cart?")) {
        $.ajax({
          type: "POST",
          url: "{% url 'cart:cart_delete' %}",
          data: {
            book_id: $(this).data("index"),
            csrfmiddlewaretoken: "{{ csrf_token }}",
            action: "post",
          },
          success: function (json) {
            location.reload();
          },
          error: function (xhr, errmsg, err) {
            console.error("Error deleting item:", errmsg);
          },
        });
      }
    });

    $(document).on("click", ".rent-book", function (e) {
      e.preventDefault();

      if (confirm("Are you sure you want to rent this book?")) {
        $.ajax({
          type: "POST",
          url: "{% url 'cart:rent_book' %}",
          data: {
            book_id: $(this).data("index"),
            csrfmiddlewaretoken: "{{ csrf_token }}",
            action: "post",
          },
          success: function (json) {
            location.reload();
          },
          error: function (xhr, errmsg, err) {
            console.error("Error renting item:", errmsg);
          },
        });
      }
    });

    $(document).on("click", "#rent-all-books", function (e) {
      e.preventDefault();

      if (confirm("Are you sure you want to rent all books in your cart?")) {
        $.ajax({
          type: "POST",
          url: "{% url 'cart:rent_all_books' %}",
          data: {
            csrfmiddlewaretoken: "{{ csrf_token }}",
            action: "post",
          },
          success: function (json) {
            location.reload();
          },
          error: function (xhr, errmsg, err) {
            console.error("Error renting all books:", errmsg);
          },
        });
      }
    });
  });
</script>

{% endblock %}