cart/urls.py
from django.urls import path
from cart.views import CartSummaryView, CartAddView, CartDeleteView, RentAllBooksView, RentBookView
app_name = "cart"
urlpatterns = [
    path('', CartSummaryView.as_view(), name='cart_summary'),
    path('add/', CartAddView.as_view(), name='cart_add'),
    path('delete/', CartDeleteView.as_view(), name='cart_delete'),
    path('rent-book/', RentBookView.as_view(), name='rent_book'),
    path('rent-all-books/', RentAllBooksView.as_view(), name='rent_all_books'),
]

django_library/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    path('cart/', include('cart.urls')),
    path('reviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from reviews.views import ReviewListView, AddReviewView, EditReviewView, DeleteReviewView

app_name = 'reviews'
urlpatterns = [
    path('list/', ReviewListView.as_view(), name='review_list'),
    path('<int:book_id>/add/', AddReviewView.as_view(), name='add_review'),
    path('edit/<int:review_id>/', EditReviewView.as_view(), name='edit_review'),
    path('delete/<int:review_id>/', DeleteReviewView.as_view(), name='delete_review'),
]

reviews/models.py
from django.db import models
from library.models import Book, CustomUser  

class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField()
    stars = models.IntegerField(choices=[(i, i) for i in range(1, 6)])

    def __str__(self):
        return f"{self.title} - {self.user.username}"

reviews/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'description', 'stars']

reviews/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views import View
from reviews.decorators import user_has_rented_book
from reviews.models import Review
from reviews.forms import ReviewForm
from library.models import Book, BookInstance 

class ReviewListView(View):
    template_name = 'review_list.html'
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request):
        reviews = Review.objects.filter(user=request.user).order_by('-id')
        return render(request, self.template_name, {'reviews': reviews})

class AddReviewView(View):
    template_name = 'add_review.html'
    
    @method_decorator(login_required)
    @method_decorator(user_has_rented_book)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, book_id):
        book = get_object_or_404(Book, id=book_id)
        form = ReviewForm()
        return render(request, self.template_name, {'form': form, 'book': book})

    def post(self, request, book_id):
        book = get_object_or_404(Book, id=book_id)
        book_instance = BookInstance.objects.filter(book=book, borrower=request.user)
        
        if not book_instance:
            messages.error(request, ("You have to rent the book to leave a review."))
            return redirect('home') 
        
        existing_review = Review.objects.filter(book=book, user=request.user).exists()
        
        if not existing_review:
            form = ReviewForm(request.POST)

            if form.is_valid():
                review = form.save(commit=False)
                review.book = book
                review.user = request.user
                review.save()
                return redirect('home')
        else:
            return redirect('home')

class EditReviewView(View):
    template_name = 'edit_review.html'
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, review_id):
        review = get_object_or_404(Review, id=review_id, user=request.user)
        form = ReviewForm(instance=review)
        return render(request, self.template_name, {'form': form, 'review': review})

    def post(self, request, review_id):
        review = get_object_or_404(Review, id=review_id, user=request.user)
        form = ReviewForm(request.POST, instance=review)

        if form.is_valid():
            form.save()
            return redirect('reviews:review_list')

        return render(request, self.template_name, {'form': form, 'review': review})


class DeleteReviewView(View):
    template_name = 'delete_review.html'
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, review_id):
        review = get_object_or_404(Review, id=review_id, user=request.user)
        return render(request, self.template_name, {'review': review})

    def post(self, request, review_id):
        review = get_object_or_404(Review, id=review_id, user=request.user)
        review.delete()
        return redirect('reviews:review_list')

reviews/templates/add_review.html
{% extends 'base.html' %}

{% block content %}
  <header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
      <div class="text-center text-white">
        <h1 class="display-4 fw-bolder">Add Review</h1>
      </div>
    </div>
  </header>
  <div class="container mt-4">
    <div class="card w-75 mx-auto p-4 shadow">
      <h2 class="mb-4">Add a Review for {{ book.title }}</h2>
      <form method="post" action="{% url 'reviews:add_review' book_id=book.id %}" class="row g-3">
        {% csrf_token %}
        <div class="col-md-6">
          {{ form.title.label_tag }}
          {{ form.title }}
        </div>
        <div class="col-md-6">
          {{ form.stars.label_tag }}
          {{ form.stars }}
        </div>
        <div class="col-12">
          {{ form.description.label_tag }}
          {{ form.description }}
        </div>
        <div class="col-12 mt-3">
          <button type="submit" class="btn btn-primary">Submit Review</button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

reviews/templates/delete_review.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-4">
    <h2>Delete Review</h2>
    <p>Are you sure you want to delete the review for "{{ review.title }}"?</p>
    <form method="post" action="{% url 'reviews:delete_review' review_id=review.id %}" class="w-50">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Delete</button>
      <a href="{% url 'reviews:review_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
  </div>
{% endblock %}

reviews/templates/edit_review.html
{% extends 'base.html' %}

{% block content %}
  <header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
      <div class="text-center text-white">
        <h1 class="display-4 fw-bolder">Edit Review</h1>
      </div>
    </div>
  </header>
  <div class="container mt-4">
    <h2>Edit Review for {{ review.title }}</h2>
    <form method="post" action="{% url 'reviews:edit_review' review_id=review.id %}" class="w-50">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Update Review</button>
    </form>
  </div>
{% endblock %}

reviews/templates/review_list.html
{% extends 'base.html' %}

{% block content %}
  <header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
      <div class="text-center text-white">
        <h1 class="display-4 fw-bolder">My Reviews</h1>
        <p class="lead fw-normal text-white-50 mb-0">View your reviews...</p>
      </div>
    </div>
  </header>
  <div class="container mt-4">
    <h2>Reviews</h2>
    {% if reviews %}
      <ul class="list-group">
        {% for review in reviews %}
          <li class="list-group-item d-flex justify-content-between align-items-center">
            {{review.book}} - {{ review.title }} - {{ review.stars }} stars
            <div>
              <a href="{% url 'reviews:edit_review' review_id=review.id %}" class="btn btn-warning btn-sm me-2">Edit</a>
              <a href="{% url 'reviews:delete_review' review_id=review.id %}" class="btn btn-danger btn-sm">Delete</a>
            </div>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>No reviews available.</p>
    {% endif %}
  </div>
{% endblock %}